### ISSUE TITLE
Last merge affected download link, affecting circleci EKS orb and likely preventing builds for many users!

### ISSUE THREAD

**Issue by wasims1** [kubernetes-sigs/aws-iam-authenticator#451] opened 2022-04-09 01:42 UTC
Hi

Today we started having error in CI/CD in Circleci. Apparently the circleci/aws-eks@2.1.1 uses aws-iam-authenticator using this command to obtain version and then using DOWNLOAD_URL:

VERSION=$(curl -Ls --fail --retry 3 -o /dev/null -w "%{url_effective}" "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest" | sed 's:.*/::' | sed 's/v//g')

DOWNLOAD_URL="https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v${VERSION}/${FILENAME}_${VERSION}_${PLATFORM}_amd64"

The variables are as follows:
PLATFORM="linux"
FILENAME="aws-iam-authenticator"

Running the DOWNLOAD_URL with version 0.5.6 works, however after today's merge and release of version 0.5.7, we are getting 404 Not found - which stopped our builds currently..

**Comment by jstastny** [comment] 2022-04-09 08:21
Looks like duplicate of https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/449

**Comment by cubean** [comment] 2022-04-09 12:15
Got the building issue with aws-ecr in CircleCI. Does anyone know how to solve it quickly? Thanks.

**Comment by trescube** [comment] 2022-04-09 14:26
Yeah, hardcode to the last known good version until this has been resolved:

```
FILENAME="aws-iam-authenticator"
VERSION=0.5.6
```

**Comment by benknight** [comment] 2022-04-09 20:18
Same issue here, broke my build.

Looks like this has happened before: https://discuss.circleci.com/t/aws-eks-orb-aws-iam-authenticator-install-fails-missing-or-malformed-url/37699

**Comment by wasims1** [comment] 2022-04-10 10:06
to anyone still having this issue, the aws-eks orb itself issued an emergency update just change the version to :2.1.2 and it should work for now...

**Comment by cubean** [comment] 2022-04-10 13:10
> to anyone still having this issue, the aws-eks orb itself issued an emergency update just change the version to :2.1.2 and it should work for now...

It's working. Thank you very much.

BTW: remember to add region if you upgrade the aws-eks version.

```
- aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: xxx
          aws-region: ${AWS_REGION}
```

**Closed** 2022-09-07 14:56 UTC
Labels: lifecycle/rotten
