### ISSUE TITLE
Bad certificate error

### ISSUE THREAD

**Issue by hugespoon** [kubernetes-sigs/aws-iam-authenticator#25] opened 2017-12-05 20:36 UTC
**Kubernetes Version**: 1.8.4

I'm attempting to give this a try in a testing cluster I've spun up with `kops 1.8.0`. I think I'm quite close, but it looks like I've got a certificate problem somewhere. When attempting to do the following, I get a few errors:

`
kubectl --kubeconfig=/path/to/my/kubeconfig --token="$(heptio-authenticator-aws token -i mycluster.local)" get nodes
`

The first is immediate on my local workstation:
`error: You must be logged in to the server (Unauthorized)`

The second is from the container itself:
`time="2017-12-05T20:14:47Z" level=info msg="http: TLS handshake error from 127.0.0.1:41980: remote error: tls: bad certificate" http=error`

I'm assuming I have the wrong certificate configured somewhere, but from the docs it is not clear where that might be. Does the authenticator need to use the cluster certificates (in this case generated by kops) or are the certs it generates on its own correct?

**Comment by mirthy** [comment] 2018-01-10 16:09
I think it's the API server not liking the fact that the heptio service is using a self-signed cert.

From the API server logs:
E0110 15:57:04.102999       6 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post https://127.0.0.1:21362/authenticate: x509: certificate signed by unknown authority]]

From the service:
time="2018-01-10T15:57:04Z" level=info msg="http: TLS handshake error from 127.0.0.1:56138: remote error: tls: bad certificate" http=error

**Comment by baniol** [comment] 2018-01-20 22:56
@hugespoon 
you're not assuming role (with `-r`) and trying to authenticate as IAM user, which is probably not mapped in ConfigMap (https://github.com/heptio/authenticator/blob/master/example.yaml#L68)

I was able to fix it after examining the logs of the heptio-authenticator pod, where I spotted:
```
time="2018-01-20T22:44:05Z" level=warning msg="access denied because ARN is not mapped" arn="arn:aws:iam::000000000000:user/my-user" client="127.0.0.1:38836" method=POST path=/authenticate
```

**Comment by KaustubhKhati** [comment] 2018-03-07 12:31
Any Update on the issue?
We too are facing the same problem only thing that is different for us is that after all the kops rolling update if we restart the docker container named

**Comment by KaustubhKhati** [comment] 2018-03-12 06:55
I have seen that after doing kops rolling update restarting the docker pod 'k8s_kube-apiserver-*' in Master worked for me rather than kubelet service. And we could automate this by adding a file asset 

> - content: |
>         sudo docker ps | grep k8s_kube-apiserver_kube-apiserver | awk {'print $1'} | xargs sudo docker restart
>       name: restart-api.sh
>       path: /srv/kubernetes/restart-api.sh
>       roles:
>         - Master

And then executing it. Dont know if its right thing to do or not

**Comment by christopherhein** [comment] 2018-04-26 16:41
@KaustubhKhati @Raffo @baniol I'm trying to better understand the issue you are running into. Are you saying that when using `kops` 1.8 and adding the webhook if the backend that it's suppose to connect to isn't alive it fails?

Or how can I best reproduce this?

**Comment by christopherhein** [comment] 2018-04-26 17:51
Also, did anyone have a chance to run through #45 to verify if that solved their problems?

**Comment by Raffo** [comment] 2018-04-26 20:27
@christopherhein I try to explain what happen to me: 

- I create an entirely new kops cluster (kops 1.9 with kubernetes 1.9.3, private+public subnets, cni mode and weave, just to add more info about the setup) with the configuration exactly as explained in https://github.com/heptio/authenticator/pull/45 
- I wait for the cluster to be healthy 
- I apply the daemonset + configmap for the authenticator
- I get unauthorized. I see the error like in the first message: `time="2017-12-05T20:14:47Z" level=info msg="http: TLS handshake error from 127.0.0.1:41980: remote error: tls: bad certificate" http=error` 
- To solve it, I ssh into the master node, do a docker stop of the apiserver container and do a `systemctl restart kubelet`. 
- From there on everything works. 

I haven't looked too much myself in trying to understand the full root cause of the issue, but it is definitely more than just annoying. Strange enough, I didn't have this issue with the a heptio quickstarter cluster.

**Comment by Raffo** [comment] 2018-04-27 14:28
I'm doing the same equivalent steps, nothing significantly different: 

My hook: 
```
hooks:
  - name: kops-hook-authenticator-config.service
    before:
      - kubelet.service
    roles: [Master]
    manifest: |
      [Unit]
      Description=Download Heptio AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/heptio-authenticator-aws
      ExecStart=/usr/bin/docker run --net=host --rm -v /srv/kubernetes/heptio-authenticator-aws:/srv/kubernetes/heptio-authenticator-aws quay.io/coreos/awscli@sha256:7b893bfb22ac582587798b011024f40871cd7424b9026595fd99c2b69492791d aws s3 cp --recursive s3://bucket/cluster/addons/authenticator /srv/kubernetes/heptio-authenticator-aws/
```

I will perform additional tests after the weekend to understand better the interactions.

**Comment by christopherhein** [comment] 2018-05-14 22:47
@Raffo any update?

**Comment by KaustubhKhati** [comment] 2018-05-17 11:01
@Raffo @christopherhein  In my case i am applying the heptio-authenticator-daemonset  first and copying the cert files to S3 bucket after that I am doing KOPS edit cluster followed by Rolling Update. This flow works for me without giving the bad certificate issue.

**Comment by Raffo** [comment] 2018-05-17 11:19
@KaustubhKhati I think that works because you are essentially restarting the API server when you do the rolling update, right?

**Comment by KaustubhKhati** [comment] 2018-05-17 12:00
@Raffo Yes

**Comment by Raffo** [comment] 2018-05-17 12:13
Ok, but this is also different from the previously provided instructions that do not have a rolling update listed.

**Comment by christopherhein** [comment] 2018-05-17 16:09
Cool, so we should be covered, agreed? can we close this?

**Comment by Raffo** [comment] 2018-05-18 06:35
@christopherhein Well, in the list of commands in this issue, you have `kops update`, AFAIK this does **not** restart the API server node, which is saying to me that we didn't find the mistery :-D I'm still okay to close this and re-open it if I find a more reliable way to verify it, unfortunately I have very little time to invest to test this.

**Comment by christopherhein** [comment] 2018-05-18 15:44
The cohesive list to get the authenticator working for a kops cluster (or any cluster) should go as follows - https://github.com/heptio/authenticator#kops-usage which includes #3 that says "If the cluster already exists, roll the cluster with `kops rolling-update cluster ${CLUSTER_NAME}` in order to recreate the master nodes."

**Comment by thedevelopnik** [comment] 2018-06-06 22:19
I've gone through all the kops steps, including the rolling update, and I'm still having this issue.

**Comment by priitpaasukene** [comment] 2019-01-16 10:16
It seems like there is some race condition when master node boots up - restarting kube-apiserver on master node after aws-iam-authenticator pod is up mitigated the the problem for me.

kops v1.11.0, k8s 1.11.6 and gcr.io/heptio-images/authenticator:v0.3.0

**Comment by mazzy89** [comment] 2019-01-16 11:37
I've solved this by configuring kops correctly. It was misconfigured because I was using in the Cluster Spec both the `authentication: aws` block and the hook as described in the documentation. Then I just removed the hook and just used the authentication block to enable the addon and install aws-iam-authenticator and it worked

**Comment by christopherhein** [comment] 2019-04-20 00:42
Now that kops has this in as a feature this should be an automated config. Closing. Please open if you are still running into issues.

/close

**Closed by christopherhein** 2019-04-20 00:42 UTC
