### ISSUE TITLE
[Bug]: Running `token` command with new SSO profile/session config format returns an error

### ISSUE THREAD

**Issue by amorey** [kubernetes-sigs/aws-iam-authenticator#606] opened 2023-06-16 19:15 UTC
### What happened?

Running token command with AWS SSO's newer profile/session config format returns an error:
```
$ export AWS_PROFILE="my-profile"
$ aws-iam-authenticator token -i my-cluster-name
could not get token: could not create session: profile "my-profile" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
```

### What you expected to happen?

`token` command to generate a token using the SSO credentials

### Anything else we need to know?

Here's what the aws config file looks like (produced by `aws configure sso`):
```
[profile my-profile]
sso_session = my-sso-session
sso_account_id = 1234567890
sso_role_name = MyRole
region = us-east-1

[sso-session my-sso-session]
sso_start_url = https://myorganization.awsapps.com/start/
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```

### Installation tooling

other (please specify in description)

### AWS IAM Authenticator client version

0.6.2

### Client information

```Markdown
- OS/arch: macOS/amd64
- kubernetes client & version: n/a
```

### Kubernetes API Version

n/a

### kubeconfig user

```JSON
n/a
```

**Comment by tapanhalani** [comment] 2023-08-23 16:09
Same thing happening with me on authenticator version 0.6.10 , using it from a WSL2 ubuntu on windows.

**Comment by vutny** [comment] 2023-08-28 13:31
This is still an issue in version 0.6.11.
It looks like the [root cause](https://github.com/aws/aws-sdk-go/issues/4649) is lying down in aws-sdk-go v1 module, but it should be fixed by this commit: https://github.com/aws/aws-sdk-go/commit/d7444686ced4167d8855e81e56e82d585f8dc0e1

Need to bump github.com/aws/aws-sdk-go at least to [v1.44.298](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.298)

**Comment by vutny** [comment] 2023-08-28 14:49
Submitted PR https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/628

**Closed** 2023-10-12 13:59 UTC
Labels: kind/bug, needs-triage
